// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package datawidgets.proxies;

public enum Enumeration_Example
{
	Example_1("f168c7dc-7a23-4d7f-b86a-7d8534830d40"),
	Example_2("c51fc301-1f60-4ad1-9636-ee142bbeed84");

	private final java.lang.String i18nCaptionKey;
	
	private Enumeration_Example(java.lang.String i18nCaptionKey)
	{
		this.i18nCaptionKey = i18nCaptionKey;
	}

	public java.lang.String getCaption(java.lang.String languageCode)
	{
		String caption = com.mendix.core.Core.getInternationalizedString(languageCode, i18nCaptionKey);
		return caption.isEmpty() ? getCaption() : caption;
	}

	public java.lang.String getCaption()
	{
		return com.mendix.core.Core.getInternationalizedString("en_GB", i18nCaptionKey);
	}
}
