// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package webactions.proxies;

public enum PictureQuality
{
	original("869c4fcd-6f9d-4582-9631-f02fff543198"),
	low("69e8ab24-db54-429b-8b8c-184d9f2fcdaa"),
	medium("81d1707b-3e71-435b-8589-3669e3ea9eab"),
	high("21ab9a81-21c3-4578-a2be-2a2ed695cbb0"),
	custom("f9d5adf2-08d2-4ae4-814a-c13762a212c3");

	private final java.lang.String i18nCaptionKey;
	
	private PictureQuality(java.lang.String i18nCaptionKey)
	{
		this.i18nCaptionKey = i18nCaptionKey;
	}

	public java.lang.String getCaption(java.lang.String languageCode)
	{
		String caption = com.mendix.core.Core.getInternationalizedString(languageCode, i18nCaptionKey);
		return caption.isEmpty() ? getCaption() : caption;
	}

	public java.lang.String getCaption()
	{
		return com.mendix.core.Core.getInternationalizedString("en_GB", i18nCaptionKey);
	}
}
