// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package unittesting.proxies;

public enum ENUM_UnitTestResult
{
	_1_Running("83444336-4771-47df-8099-a55551d42025"),
	_2_Failed("4e99ed7c-4bb9-44a4-b2a8-d83aadebc2a1"),
	_3_Success("af8a68e2-449b-44fc-ae02-8d540fe0de67");

	private final java.lang.String i18nCaptionKey;
	
	private ENUM_UnitTestResult(java.lang.String i18nCaptionKey)
	{
		this.i18nCaptionKey = i18nCaptionKey;
	}

	public java.lang.String getCaption(java.lang.String languageCode)
	{
		String caption = com.mendix.core.Core.getInternationalizedString(languageCode, i18nCaptionKey);
		return caption.isEmpty() ? getCaption() : caption;
	}

	public java.lang.String getCaption()
	{
		return com.mendix.core.Core.getInternationalizedString("en_GB", i18nCaptionKey);
	}
}
