// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package nanoflowcommons.proxies;

public enum GeocodingProvider
{
	Google("cee99c0e-845c-450c-a18d-f1269996f807"),
	Geocodio("39570b5d-29bc-4b1a-84dc-fb6aeba15db0"),
	LocationIQ("0cb5ef82-ecda-4269-a306-9e4dfd025b73"),
	MapQuest("a4a4b6f3-c702-4cf8-8ce4-f8222e3fab67");

	private final java.lang.String i18nCaptionKey;
	
	private GeocodingProvider(java.lang.String i18nCaptionKey)
	{
		this.i18nCaptionKey = i18nCaptionKey;
	}

	public java.lang.String getCaption(java.lang.String languageCode)
	{
		String caption = com.mendix.core.Core.getInternationalizedString(languageCode, i18nCaptionKey);
		return caption.isEmpty() ? getCaption() : caption;
	}

	public java.lang.String getCaption()
	{
		return com.mendix.core.Core.getInternationalizedString("en_GB", i18nCaptionKey);
	}
}
