// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package nanoflowcommons.proxies;

public enum Platform
{
	Web("4acea2f9-8532-471a-b0e3-0a2b03a3ff48"),
	Native_mobile("93628b40-00f5-4f97-9d83-79f33fb36240"),
	Hybrid_mobile("f864d755-fe8c-4570-acfb-cb45fa55ebe5");

	private final java.lang.String i18nCaptionKey;
	
	private Platform(java.lang.String i18nCaptionKey)
	{
		this.i18nCaptionKey = i18nCaptionKey;
	}

	public java.lang.String getCaption(java.lang.String languageCode)
	{
		String caption = com.mendix.core.Core.getInternationalizedString(languageCode, i18nCaptionKey);
		return caption.isEmpty() ? getCaption() : caption;
	}

	public java.lang.String getCaption()
	{
		return com.mendix.core.Core.getInternationalizedString("en_GB", i18nCaptionKey);
	}
}
